-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               8.0.30 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table data_svm.data_latih
CREATE TABLE IF NOT EXISTS `data_latih` (
  `id` int NOT NULL AUTO_INCREMENT,
  `Nama_Keluarga` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Alamat` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Kabupaten` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Kecamatan` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Pendapatan_Per_Bulan` int DEFAULT NULL,
  `Jenis_Pekerjaan` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Riwayat_Penyakit_Kronis` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Tingkat_Pendidikan` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Status_Kepemilikan_Rumah` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Kehilangan_Mata_Pencaharian` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Anggota_Keluarga_Rentan` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Tidak_Menerima_Bantuan_Sosial` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Rumah_Tangga_Lansia_Tunggal` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Perempuan_Kepala_Keluarga` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Kategori` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=401 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table data_svm.data_latih: ~400 rows (approximately)
INSERT INTO `data_latih` (`id`, `Nama_Keluarga`, `Alamat`, `Kabupaten`, `Kecamatan`, `Pendapatan_Per_Bulan`, `Jenis_Pekerjaan`, `Riwayat_Penyakit_Kronis`, `Tingkat_Pendidikan`, `Status_Kepemilikan_Rumah`, `Kehilangan_Mata_Pencaharian`, `Anggota_Keluarga_Rentan`, `Tidak_Menerima_Bantuan_Sosial`, `Rumah_Tangga_Lansia_Tunggal`, `Perempuan_Kepala_Keluarga`, `Kategori`) VALUES
	(1, 'PURWANTO SADI ', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(2, 'AINUL RIZA', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(3, 'BUJANG ITING', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Ya', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Layak'),
	(4, 'HENDRA', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SD', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(5, 'ESTER G', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 2000000, 'Pekerja Tambang', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(6, 'MARIA FRANSISCA', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak Layak'),
	(7, 'RICKY RAMADHAN', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(8, 'JUNAIDI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(9, 'ROFIAH ', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Ya', 'Ya', 'Layak'),
	(10, 'BUR\'IN', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(11, 'LEO', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Petani', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(12, 'IWANALI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(13, 'ERNI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(14, 'KARTINI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Ya', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(15, 'HUSEN TAHIR', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Ya', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(16, 'ABDUL ASAT', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Ya', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(17, 'TRI HANDAYANI', 'Bantayan', 'Aceh Timur', 'Nurussalam', 2000000, 'Petani', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(18, 'JAMHUR YUNUS', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak Layak'),
	(19, 'SUHENDI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(20, 'AGUN SUNARTO', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Tidak', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(21, 'TABRANI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 2000000, 'Pekerja Tambang', 'Ya', 'SD', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(22, 'EDI TRIYANTO', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Ya', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(23, 'ERNI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(24, 'ISWANDI', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Ya', 'SMP', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Layak'),
	(25, 'NURMIATI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(26, 'GADIK SIRI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 500000, 'Kuli Bangunan', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(27, 'RUSTIAN', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak Layak'),
	(28, 'SAMSIAR SIDER', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(29, 'JAMALUDIN', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(30, 'DEFI NIZAM', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(31, 'AMZAR MUHAMMAD ASIP', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(32, 'IWAN', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Ya', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(33, 'SA\'DIAH CALISTA', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(34, 'SYUKUR', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Ya', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(35, 'AGUS ARIANDI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 2000000, 'Pekerja Tambang', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(36, 'FEBRIANDI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak Layak'),
	(37, 'SURIYANTO RAJINI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(38, 'ROMI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(39, 'SURYADI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(40, 'KHAIRANI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(41, 'MISNO NORNI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 500000, 'Tukang', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(42, 'SYAYED', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(43, 'ZULKIFLI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Petani', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(44, 'INDRA WIJAYA', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 2000000, 'Kuli Bangunan', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(45, 'JUPRIADI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 500000, 'Pekerja Tambang', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak Layak'),
	(46, 'HENDRI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Tidak', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak Layak'),
	(47, 'NOPIANTO', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(48, 'PARINO SIDUK', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(49, 'RIYAN', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 2000000, 'Buruh', 'Tidak', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(50, 'EKI', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SD', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(51, 'GUSMAYADI', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Petani', 'Ya', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(52, 'LENI LESTARI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 2000000, 'Kuli Bangunan', 'Ya', 'SMP', 'Sewa', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(53, 'PENDI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Tidak', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(54, 'JOFI ZAINUDIN', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(55, 'EDDY SISWANTO', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak Layak'),
	(56, 'JULAYHI SUPARDI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 500000, 'Tukang', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(57, 'MUHDI', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Ya', 'Layak'),
	(58, 'SILVIA EKA LIESTOYO', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 2000000, 'Buruh', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak Layak'),
	(59, 'MARGI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Petani', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(60, 'GENTUR BUDI SUSILO WIBOWO', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 2000000, 'Tukang', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak Layak'),
	(61, 'HENNY', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(62, 'JUPRIADI', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Ya', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(63, 'ADI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(64, 'URAY BESTARI MUZANNI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 2000000, 'Pekerja Tambang', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak Layak'),
	(65, 'DIKA', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 500000, 'Petani', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(66, 'JEKI SARIFUDIN', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Petani', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(67, 'MARZUKI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 500000, 'Petani', 'Ya', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Ya', 'Ya', 'Layak'),
	(68, 'GUSTIAR', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Ya', 'Layak'),
	(69, 'GUSTIANTO', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 2000000, 'Petani', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(70, 'RAHMAT SALITOT', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 2000000, 'Tukang', 'Ya', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(71, 'HARDI SUMANTO', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Ya', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(72, 'MAJID BUHARI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 500000, 'Petani', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Ya', 'Layak'),
	(73, 'EPI KARIM', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 2000000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(74, 'NELI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak Layak'),
	(75, 'SAFARI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak', 'Tidak Layak'),
	(76, 'HENDRA SEDANG', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Ya', 'SD', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Layak'),
	(77, 'ANDI LALA SANI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 2000000, 'Buruh', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(78, 'ISWANTO', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Ya', 'SMP', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(79, 'JEFRI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Ya', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Layak'),
	(80, 'JOKO EDANG', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Tidak', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(81, 'IRAWATI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Petani', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(82, 'MUHAMAD SIRYADI BN SADIRO SENA', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Ya', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(83, 'SYUKUR', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 2000000, 'Buruh', 'Ya', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Layak'),
	(84, 'PARINO SIDUK', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak Layak'),
	(85, 'FERIAJI YUHANA', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(86, 'DIRMANSYAH ARMIN', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(87, 'RUDIANTO', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 500000, 'Kuli Bangunan', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(88, 'LIU MUI FA', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Ya', 'SD', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(89, 'FEBRIANTO SUWARDI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(90, 'GUSPINAL', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(91, 'AGUSTINUS TEFA', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 500000, 'Kuli Bangunan', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak Layak'),
	(92, 'RANO', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Ya', 'SD', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Layak'),
	(93, 'MUHAMMAD KHOIFIN', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak Layak'),
	(94, 'NOPIANTO', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Ya', 'SD', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(95, 'SIAUW PIT CHUNG', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(96, 'KHAIRANI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 500000, 'Tukang', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak', 'Tidak Layak'),
	(97, 'UDITYA YUSTIARSO', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 2000000, 'Pembantu', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(98, 'SURYA', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Ya', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(99, 'TABRANI', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SD', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(100, 'ANDI HERMAWAN ', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(101, 'BILY YULIANTO', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Ya', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(102, 'EVI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(103, 'HABIB MAULANA SINAGA', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(104, 'MITA RAHMAWATI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 2000000, 'Pembantu', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(105, 'SUNARTO', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SD', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(106, 'SURYANTO', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 2000000, 'Pekerja Tambang', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(107, 'GUSTIANTO', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 500000, 'Petani', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(108, 'IWANALI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 2000000, 'Pekerja Tambang', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(109, 'FINO MUSRID', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 2000000, 'Buruh', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(110, 'KHAIRANI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 2000000, 'Tukang', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(111, 'DARMANTO', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(112, 'YULIUS', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 500000, 'Pekerja Tambang', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak Layak'),
	(113, 'HERDIAN', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Tidak', 'SMP', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(114, 'GUSTIAN', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 2000000, 'Buruh', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(115, 'LEO', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(116, 'ERWIN PENDI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Ya', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(117, 'RURAT', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 2000000, 'Tukang', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(118, 'JEKI SARIFUDIN', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Petani', 'Tidak', 'SMP', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(119, 'UMI LATIFAH', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 2000000, 'Tukang', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(120, 'FINO MUSRID', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(121, 'JUMADI NAJAM', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(122, 'SALIFASHTUL', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(123, 'KON KIM CHIAN', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak Layak'),
	(124, 'ERLANGGA', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Ya', 'SD', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(125, 'GUSPIANDI ZAINI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Petani', 'Ya', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(126, 'RAHMAT SALITOT', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(127, 'WARDI DAMIRI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(128, 'RAHMAT ASNI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Ya', 'SD', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(129, 'EPI KARIM', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 500000, 'Tukang', 'Tidak', 'SD', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak Layak'),
	(130, 'EKO SLAMET WIDODO', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(131, 'SARWONO AMSAR', 'Bantayan', 'Aceh Timur', 'Nurussalam', 2000000, 'Tukang', 'Ya', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(132, 'IRMA. Y', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 2000000, 'Pembantu', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(133, 'DEWI YUDHA AMALIASARI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SD', 'Sewa', 'Ya', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(134, 'IMAT ', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SD', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak Layak'),
	(135, 'DIKA', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Petani', 'Tidak', 'SMP', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(136, 'ANTON', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Ya', 'SD', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Ya', 'Ya', 'Layak'),
	(137, 'MUSLIHAN MAHYUS', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 500000, 'Tukang', 'Ya', 'SMA', 'Sewa', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(138, 'LIDIANSYAH MURNI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(139, 'RINO', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 2000000, 'Pekerja Tambang', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(140, 'AGUS ARIANDI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Ya', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Ya', 'Ya', 'Layak'),
	(141, 'HARDI SUMANTO', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 2000000, 'Petani', 'Ya', 'SMP', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Layak'),
	(142, 'WAHYUDI HARI KRISTANTO', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(143, 'JAMEL ASDI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak Layak'),
	(144, 'SURJA PARNI', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SMP', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(145, 'MUHARDI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 2000000, 'Tukang', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak Layak'),
	(146, 'PEBRIANTO', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(147, 'MOCH MUCHLASIN', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(148, 'GUSTIAN', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 500000, 'Pembantu', 'Ya', 'SMA', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(149, 'MUHDI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 500000, 'Kuli Bangunan', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(150, 'SURYA ILDANA', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 500000, 'Kuli Bangunan', 'Ya', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(151, 'DONI JUSRI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Ya', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(152, 'AHMAD GAZALI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(153, 'JEKI SARIFUDIN', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(154, 'JUMADI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Ya', 'SMA', 'Sewa', 'Ya', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(155, 'UMAR', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Ya', 'Ya', 'Layak'),
	(156, 'DARMADI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 500000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(157, 'PURWANTO SADI ', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(158, 'HERWAN', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak Layak'),
	(159, 'MAYADI', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Tidak', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(160, 'BUDI KARIM', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 500000, 'Pekerja Tambang', 'Ya', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(161, 'RUSDIANTO', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 500000, 'Petani', 'Ya', 'SMP', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(162, 'FERIAJI YUHANA', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak Layak'),
	(163, 'GUSMAYADI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(164, 'ROBIN', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Ya', 'Layak'),
	(165, 'DONI JUSRI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(166, 'KASNO SUAIDI', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 500000, 'Pembantu', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(167, 'AMAT PAWADI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SMP', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(168, 'LAMSAH', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SD', 'Sewa', 'Ya', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(169, 'JEFRI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(170, 'JAMADI JAMIAN', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(171, 'WAHARI MAHLI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak Layak'),
	(172, 'SLAMET MAHFUR', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(173, 'MASLAN GUNAWAN', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Ya', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(174, 'WIDAYANTI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(175, 'KETEL GINTO ASRIN', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 2000000, 'Pembantu', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Layak'),
	(176, 'AINUL RIZA', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Petani', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(177, 'SUDIRMAN', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Ya', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(178, 'JULINAWATI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Ya', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(179, 'HENGKY PRAMADAN', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(180, 'ADE SAPUTRA', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 2000000, 'Buruh', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak Layak'),
	(181, 'SURIADI', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(182, 'SYARIFAH DESI EKA', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 2000000, 'Buruh', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak Layak'),
	(183, 'PUTRO WASONO', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(184, 'IRAS', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(185, 'SAHDAN SARIAT', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 500000, 'Tukang', 'Ya', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Ya', 'Layak'),
	(186, 'UMAR ABDUL', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(187, 'DAHLIA HAIDIR', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(188, 'LAMSYAH', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(189, 'ISKANDAR', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(190, 'SANDIKA PARMAN', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Ya', 'SMP', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(191, 'JUNAIDA', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 500000, 'Petani', 'Tidak', 'SD', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(192, 'DIDANG DARMADI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Petani', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(193, 'ERLANGGA', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(194, 'MATORI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Ya', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(195, 'JEFRI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(196, 'AAN SUTIAWAN', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(197, 'GUSMAYADI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 500000, 'Kuli Bangunan', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(198, 'NURSALIM', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(199, 'PARDI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Ya', 'SMP', 'Sewa', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(200, 'ALI HAMDI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(201, 'YANTI JAWI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 500000, 'Petani', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Layak'),
	(202, 'FARDIYANSYAH', 'Bantayan', 'Aceh Timur', 'Nurussalam', 2000000, 'Buruh', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(203, 'WALDI MASBU', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(204, 'UDITYA YUSTIARSO', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Ya', 'SD', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(205, 'NAZIRIN', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 2000000, 'Tukang', 'Ya', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(206, 'AMAT', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(207, 'URAY DENI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Petani', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(208, 'MELKY SOJIT SAIDUN', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(209, 'MUCHUS ARIYADI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak Layak'),
	(210, 'MUHAMMAD KUSNA ARIEF SETIAWAN', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak Layak'),
	(211, 'HOBES', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(212, 'SHOLIKHIN', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(213, 'URAY BESTARI MUZANNI', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(214, 'RIZAL', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Tidak', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(215, 'DONI JUSRI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SMA', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak Layak'),
	(216, 'MUNDZAKIR', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Ya', 'Layak'),
	(217, 'DEDI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 2000000, 'Tukang', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak Layak'),
	(218, 'JANAWAR', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(219, 'SAMSUL LIAS DANGGUN', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 500000, 'Pekerja Tambang', 'Tidak', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(220, 'NAIDI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(221, 'HENDRI A', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Tidak', 'SMP', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(222, 'NURAINI', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Tidak Layak'),
	(223, 'JULIAN', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 2000000, 'Tukang', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(224, 'ASMAWI', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(225, 'INDRA WIJAYA', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SMP', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(226, 'MAT NASIR', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(227, 'ADI DARWANTO', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 500000, 'Pekerja Tambang', 'Ya', 'SD', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(228, 'BUDI KARIM', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(229, 'HUSEN TAHIR', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(230, 'LUXMAN', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 500000, 'Petani', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(231, 'ANDI MORNI', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(232, 'ANDI IRAWAN', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(233, 'DESI SUSANTI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak Layak'),
	(234, 'MAJID BUHARI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(235, 'UCU ALI MASTUR', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak Layak'),
	(236, 'FARLA FAURITA', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 2000000, 'Pembantu', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(237, 'SAHDAN SARIAT', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(238, 'NASRULLAH', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(239, 'AGUSTINUS TEFA', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 500000, 'Kuli Bangunan', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Tidak Layak'),
	(240, 'BAMBANG YUDOTOMO', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Tidak', 'SD', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(241, 'PEBRIANTO', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Ya', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak Layak'),
	(242, 'BENI', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Tidak', 'SD', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Ya', 'Ya', 'Layak'),
	(243, 'MARZUKI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(244, 'JULIAN', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Ya', 'SMP', 'Sewa', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(245, 'SA\'DIAH CALISTA', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 500000, 'Petani', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Layak'),
	(246, 'FADLAN', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Tidak', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(247, 'ISWADI ACHMAD', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Ya', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(248, 'GUSMAYADI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Ya', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(249, 'WILDAN', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Ya', 'Layak'),
	(250, 'EEN SURIADI HAMIDI', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Ya', 'SMP', 'Sewa', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(251, 'SARNI TARMIJI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 2000000, 'Tukang', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(252, 'RUSMINI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 2000000, 'Petani', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(253, 'GUSTIAN', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 500000, 'Kuli Bangunan', 'Ya', 'SMA', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(254, 'LENI LESTARI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(255, 'WIDIASARI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 2000000, 'Buruh', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak Layak'),
	(256, 'WIDARSA', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Ya', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak Layak'),
	(257, 'LUXMAN', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(258, 'MUSLIHAN MAHYUS', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Petani', 'Ya', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(259, 'DARMANTO', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(260, 'WIDAYANTI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Ya', 'SD', 'Sewa', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(261, 'FARDIYANSYAH', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak Layak'),
	(262, 'ERWIN', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(263, 'HENGKI RAMADHAN', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 500000, 'Tukang', 'Ya', 'SMP', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(264, 'HABIB MAULANA SINAGA', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 2000000, 'Tukang', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(265, 'SAMODI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 2000000, 'Pekerja Tambang', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(266, 'RABULI', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(267, 'PRASTIYA BENI SYAPIRI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 500000, 'Pekerja Tambang', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(268, 'FADLAN FADLIL', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 2000000, 'Buruh', 'Ya', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Tidak Layak'),
	(269, 'DIRMANSYAH ARMIN', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(270, 'RUSLI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(271, 'ROMI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Ya', 'SD', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(272, 'PATRIA LIAS', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Tidak', 'SD', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(273, 'ERNI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Ya', 'SD', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Ya', 'Ya', 'Layak'),
	(274, 'JOHANDI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(275, 'FEBRIYANTI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 500000, 'Pekerja Tambang', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak Layak'),
	(276, 'MUSLIMIN', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Ya', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(277, 'DAHLIA HAIDIR', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(278, 'AMIR', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak Layak'),
	(279, 'SULISTIYONO', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak Layak'),
	(280, 'SUPARDI MUAZZI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak Layak'),
	(281, 'HABIB MAULANA SINAGA', 'Bantayan', 'Aceh Timur', 'Nurussalam', 2000000, 'Petani', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(282, 'MAJID BUHARI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Ya', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(283, 'TRI HANDAYANI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 500000, 'Pembantu', 'Ya', 'SMA', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(284, 'SURJA PARNI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(285, 'RURAT', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(286, 'JUMADI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(287, 'DUWI ANGGA', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(288, 'HENNY', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak Layak'),
	(289, 'SAKA UMAR', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(290, 'ASMAWI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Tidak', 'SD', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak Layak'),
	(291, 'RINO', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 2000000, 'Buruh', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(292, 'ERI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 500000, 'Pembantu', 'Ya', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(293, 'BINARJA', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Ya', 'SD', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(294, 'ABDUL ASAT', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(295, 'RABUDIN', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak Layak'),
	(296, 'RAHMAT SALITOT', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Ya', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(297, 'ESWAANDI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 2000000, 'Pembantu', 'Ya', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(298, 'SITI ASTINI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Ya', 'SMP', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(299, 'ROBIN', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 2000000, 'Pekerja Tambang', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Ya', 'Layak'),
	(300, 'SAMSUDIN', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Petani', 'Ya', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(301, 'AMAT ASMADI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak Layak'),
	(302, 'JOKO WIOTO JAHAR', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 2000000, 'Pembantu', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(303, 'NELI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(304, 'RUSMINI', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Ya', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(305, 'ROMAN', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(306, 'RICKY RAMADHAN', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 500000, 'Kuli Bangunan', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(307, 'HENDRA', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(308, 'AKENG SUPRIADI', 'Bantayan', 'Aceh Timur', 'Nurussalam', 2000000, 'Buruh', 'Tidak', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak Layak'),
	(309, 'HAIYUDI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 2000000, 'Buruh', 'Ya', 'SMA', 'Sewa', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(310, 'MARHAZI', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(311, 'FARLA FAURITA', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(312, 'SURIYAH', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Petani', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(313, 'AGUS ARIANDI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SD', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(314, 'JAMEL ASDI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Ya', 'SD', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(315, 'GUNTUR', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 500000, 'Tukang', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Ya', 'Layak'),
	(316, 'WIDI', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 2000000, 'Pembantu', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Layak'),
	(317, 'BUR\'IN', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(318, 'SYAHBANDI', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(319, 'EVI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(320, 'MUNZIRI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 500000, 'Pekerja Tambang', 'Tidak', 'SD', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(321, 'FADLAN', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(322, 'DONA EKO APRIYANTO', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(323, 'MATSARI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 2000000, 'Pekerja Tambang', 'Ya', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Layak'),
	(324, 'HAMKA SABIRIN', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 2000000, 'Petani', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Ya', 'Ya', 'Layak'),
	(325, 'FEBRIANDI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1000000, 'Petani', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(326, 'RICKY RAMADHAN', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 500000, 'Petani', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(327, 'JAMHUR YUNUS', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(328, 'FEBRIANDI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(329, 'FIRMAN SABHI YAUMAR', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Ya', 'SD', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Layak'),
	(330, 'WAHARI MAHLI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(331, 'WAWAN RAHMADI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Ya', 'SMA', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(332, 'HERWANDI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 500000, 'Petani', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(333, 'DARUL', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(334, 'SURIADI', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Ya', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(335, 'ENDANG', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(336, 'EGI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Tidak', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(337, 'MALDINI MAWARDI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 2000000, 'Pembantu', 'Ya', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(338, 'ROMI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Tidak', 'SMA', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak Layak'),
	(339, 'MATAHARI VENNI. C', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Ya', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(340, 'YUSPIKAL', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(341, 'BUDIMAN', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Ya', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(342, 'ISKANDAR', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(343, 'MATHANIN', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(344, 'KETEL GINTO ASRIN', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 500000, 'Kuli Bangunan', 'Ya', 'SMP', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(345, 'RIDWAN UMAR', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(346, 'JOKO', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(347, 'AKENG SUPRIADI', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Ya', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(348, 'BENI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Ya', 'SMA', 'Sewa', 'Ya', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(349, 'MAULUDIN HAIRI', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1000000, 'Petani', 'Ya', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(350, 'YANTI JAWI', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Ya', 'SMP', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(351, 'SA\'DIAH CALISTA', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 2000000, 'Buruh', 'Ya', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Layak'),
	(352, 'FERLI ENAN', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Ya', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(353, 'NAIDI', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(354, 'JUMADI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 2000000, 'Kuli Bangunan', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak Layak'),
	(355, 'USMAN KAMAL', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 500000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(356, 'SUHENDRI SIMAT', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 2000000, 'Pekerja Tambang', 'Tidak', 'SD', 'Sewa', 'Ya', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(357, 'DARMADI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Tidak', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak Layak'),
	(358, 'ELLA SEKARSARI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Ya', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(359, 'SUDI SALIMAH', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Layak'),
	(360, 'JUMADI NAJAM', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Ya', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(361, 'ASTUTI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 2000000, 'Kuli Bangunan', 'Ya', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(362, 'ARMANTO', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(363, 'MUHAMMAD KUSNA ARIEF SETIAWAN', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(364, 'PUTRO WASONO', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Layak'),
	(365, 'UDITYA YUSTIARSO', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Ya', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Ya', 'Ya', 'Layak'),
	(366, 'ITA HARYANTI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Tidak', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(367, 'NURAINI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 2000000, 'Tukang', 'Tidak', 'SD', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(368, 'DESI SUSANTI', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak Layak'),
	(369, 'WENDI', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(370, 'NUR KHOLIQ', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 2000000, 'Kuli Bangunan', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Layak'),
	(371, 'SISMIYATI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 500000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(372, 'SYAMSINAR', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Ya', 'SMP', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Layak'),
	(373, 'BERENDA', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(374, 'ISWADI ACHMAD', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak Layak'),
	(375, 'WALUDI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 2000000, 'Kuli Bangunan', 'Tidak', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(376, 'MAT AFIFI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(377, 'SURYANTO', 'Bantayan', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak Layak'),
	(378, 'SUHENDI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Layak'),
	(379, 'HALDI ARIFIN', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(380, 'DESI ANDRIANI FIRDAUS', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Ya', 'SD', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(381, 'RUDI AKBAR', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(382, 'EVI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(383, 'DESI TARMUJI', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya', 'Layak'),
	(384, 'ARDIANSYAH', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 500000, 'Pembantu', 'Ya', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(385, 'DIDANG DARMADI', 'Keude Bagok sa', 'Aceh Timur', 'Nurussalam', 2000000, 'Tukang', 'Tidak', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(386, 'SAHDAN ', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(387, 'MATSARI', 'Bantayan', 'Aceh Timur', 'Nurussalam', 2000000, 'Buruh', 'Ya', 'SD', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Layak'),
	(388, 'ASTUTI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 2000000, 'Buruh', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(389, 'RAHMAT SALITOT', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Ya', 'SMP', 'Sewa', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(390, 'KON KIM CHIAN', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(391, 'RICKY EFENDI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak', 'Tidak Layak'),
	(392, 'KRISYANTO', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 500000, 'Kuli Bangunan', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(393, 'BAKHTIAR MA\'ARIF', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Layak'),
	(394, 'WALUDI', 'Keude Bagok dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Ya', 'SMP', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya', 'Layak'),
	(395, 'MUSLIYADI', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 2000000, 'Pekerja Tambang', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Ya', 'Layak'),
	(396, 'SYUKUR', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 500000, 'Pekerja Tambang', 'Tidak', 'SD', 'Sewa', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(397, 'HIDAYAT JURNI', 'Matang seuleumak', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Ya', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak'),
	(398, 'JOKO WIOTO JAHAR', 'Kuala bagok', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Ya', 'Layak'),
	(399, 'SIAUW PIT CHUNG', 'Teupin puka', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak Layak'),
	(400, 'ABDUL SAMSUDIN', 'Asan tanjong', 'Aceh Timur', 'Nurussalam', 500000, 'Kuli Bangunan', 'Ya', 'SD', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak', 'Layak');

-- Dumping structure for table data_svm.data_uji
CREATE TABLE IF NOT EXISTS `data_uji` (
  `id` int NOT NULL AUTO_INCREMENT,
  `Nama_Keluarga` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Alamat` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Kabupaten` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Kecamatan` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Pendapatan_Per_Bulan` int DEFAULT NULL,
  `Jenis_Pekerjaan` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Riwayat_Penyakit_Kronis` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Tingkat_Pendidikan` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Status_Kepemilikan_Rumah` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Kehilangan_Mata_Pencaharian` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Anggota_Keluarga_Rentan` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Tidak_Menerima_Bantuan_Sosial` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Rumah_Tangga_Lansia_Tunggal` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Perempuan_Kepala_Keluarga` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=211 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table data_svm.data_uji: ~149 rows (approximately)
INSERT INTO `data_uji` (`id`, `Nama_Keluarga`, `Alamat`, `Kabupaten`, `Kecamatan`, `Pendapatan_Per_Bulan`, `Jenis_Pekerjaan`, `Riwayat_Penyakit_Kronis`, `Tingkat_Pendidikan`, `Status_Kepemilikan_Rumah`, `Kehilangan_Mata_Pencaharian`, `Anggota_Keluarga_Rentan`, `Tidak_Menerima_Bantuan_Sosial`, `Rumah_Tangga_Lansia_Tunggal`, `Perempuan_Kepala_Keluarga`) VALUES
	(13, 'SULAIMAN', 'Bantayan Timur', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Ya'),
	(14, 'MULYADI', 'Blang Rambong', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Ya', 'SD', 'Sewa', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya'),
	(18, 'WENDI', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Ya', 'SD', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya'),
	(21, 'NOPIANTO', 'Arul Pinang', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak'),
	(22, 'HERDIAN', 'Jalan Dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak'),
	(23, 'DONA EKO APRIYANTO', 'Alue Jagat', 'Aceh Timur', 'Nurussalam', 500000, 'Pekerja Tambang', 'Ya', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Ya', 'Ya'),
	(24, 'ERNI', 'Alue Dua Muka O', 'Aceh Timur', 'Nurussalam', 2000000, 'Tukang', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak'),
	(25, 'JAMRI', 'Gunong Putoh', 'Aceh Timur', 'Nurussalam', 500000, 'Pekerja Tambang', 'Tidak', 'SMA', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak'),
	(26, 'NOPIANTO', 'Buket Drien', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak'),
	(28, 'ARDI', 'Arul Pinang', 'Aceh Timur', 'Nurussalam', 500000, 'Petani', 'Tidak', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Ya'),
	(29, 'HAMKA SABIRIN', 'Buket Peulawi', 'Aceh Timur', 'Nurussalam', 2000000, 'Pekerja Tambang', 'Tidak', 'SD', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Tidak'),
	(31, 'MASLAN GUNAWAN', 'Bukit Tiga', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Ya', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Ya', 'Ya'),
	(32, 'BUJANG IDRIS', 'Jalan Dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Petani', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya'),
	(35, 'SARWONO AMSAR', 'Alue Dua Muka O', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Tidak', 'SD', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak'),
	(38, 'SAMSIAR SIDER', 'Arul Pinang', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak'),
	(41, 'ADITYA JULI NUGROHO', 'Buket Peulawi', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Ya'),
	(43, 'JUANDA', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SMP', 'Sewa', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya'),
	(48, 'AAN SUTIAWAN', 'Jalan Dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Ya'),
	(51, 'TOMY', 'Peunaron Lama', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak'),
	(53, 'NINARI', 'Peunaron Lama', 'Aceh Timur', 'Nurussalam', 500000, 'Petani', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak'),
	(56, 'REMO SAPUTRA', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya'),
	(57, 'FIRMAN SABHI YAUMAR', 'Blang Rambong', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Ya', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Ya'),
	(58, 'IMAN', 'Alue Jagat', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Ya', 'SD', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Ya'),
	(60, 'LIU MUI FA', 'Peunaron Lama', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Ya', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Ya'),
	(61, 'MUHDI', 'Bantayan Timur', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Ya'),
	(66, 'MASLAN GUNAWAN', 'Gunong Putoh', 'Aceh Timur', 'Nurussalam', 2000000, 'Petani', 'Ya', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak'),
	(67, 'RURAT', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya'),
	(70, 'HADNI HAIRUDIN', 'Peunaron Lama', 'Aceh Timur', 'Nurussalam', 2000000, 'Kuli Bangunan', 'Tidak', 'SD', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Ya', 'Ya'),
	(72, 'HAIYUDI', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak'),
	(73, 'SUPARDI', 'Peunaron Lama', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya'),
	(75, 'MUHAMMAD ASLAN', 'Alue Dua Muka O', 'Aceh Timur', 'Nurussalam', 2000000, 'Pembantu', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Ya'),
	(78, 'JUANDA', 'Bantayan Timur', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Ya'),
	(79, 'ALDIANSYAH RIDWAN', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 500000, 'Pekerja Tambang', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak'),
	(80, 'SURYANTO', 'Blang Rambong', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Ya', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Ya', 'Ya'),
	(82, 'SULAIMAN', 'Bantayan Timur', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak'),
	(83, 'MUSPA ', 'Jalan Dua', 'Aceh Timur', 'Nurussalam', 2000000, 'Kuli Bangunan', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya'),
	(86, 'MUHAMMAD KHOIFIN', 'Buket Peulawi', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Ya', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya'),
	(88, 'PUTRO WASONO', 'Arul Pinang', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Tidak', 'SD', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Ya'),
	(90, 'REMO SAPUTRA', 'Buket Peulawi', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Ya'),
	(91, 'BAKHTIAR MA\'ARIF', 'Bantayan Timur', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak'),
	(95, 'DAVID DWI LIESTOYO', 'Peunaron Lama', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Ya', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya'),
	(98, 'SALIFASHTUL', 'Blang Rambong', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak'),
	(100, 'RUSLI DURANI', 'Alue Dua Muka O', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SD', 'Sewa', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya'),
	(101, 'YUNITA', 'Jalan Dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Ya'),
	(102, 'DESI TARMUJI', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Ya'),
	(104, 'ENDANG', 'Blang Rambong', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Ya'),
	(108, 'JANAWAR', 'Buket Peulawi', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak'),
	(109, 'ANDI MORNI', 'Arul Pinang', 'Aceh Timur', 'Nurussalam', 500000, 'Kuli Bangunan', 'Ya', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya'),
	(110, 'ZULKARNAEN', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak'),
	(111, 'ZULKIFLI', 'Alue Jagat', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Ya', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Ya'),
	(112, 'SAMSUDIN', 'Buket Peulawi', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya'),
	(113, 'SULAIMAN', 'Bantayan Timur', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Ya'),
	(114, 'MULYADI', 'Blang Rambong', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Ya', 'SD', 'Sewa', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya'),
	(115, 'TENGKU SHAHINDRA', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Ya', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Tidak'),
	(116, 'JUMADI NAJAM', 'Peunaron Lama', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak'),
	(117, 'ITA HARYANTI', 'Blang Rambong', 'Aceh Timur', 'Nurussalam', 500000, 'Kuli Bangunan', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak'),
	(118, 'WENDI', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Ya', 'SD', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya'),
	(119, 'YUNITA', 'Jalan Dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Pembantu', 'Ya', 'SD', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak'),
	(120, 'SARWONO AMSAR', 'Gunong Putoh', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Ya', 'Ya'),
	(121, 'NOPIANTO', 'Arul Pinang', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak'),
	(122, 'HERDIAN', 'Jalan Dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak'),
	(123, 'DONA EKO APRIYANTO', 'Alue Jagat', 'Aceh Timur', 'Nurussalam', 500000, 'Pekerja Tambang', 'Ya', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Ya', 'Ya'),
	(124, 'ERNI', 'Alue Dua Muka O', 'Aceh Timur', 'Nurussalam', 2000000, 'Tukang', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak'),
	(125, 'JAMRI', 'Gunong Putoh', 'Aceh Timur', 'Nurussalam', 500000, 'Pekerja Tambang', 'Tidak', 'SMA', 'Milik Sendiri', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak'),
	(126, 'NOPIANTO', 'Buket Drien', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak'),
	(127, 'DEDI', 'Jalan Dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Ya', 'SMA', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak'),
	(128, 'ARDI', 'Arul Pinang', 'Aceh Timur', 'Nurussalam', 500000, 'Petani', 'Tidak', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Ya'),
	(129, 'HAMKA SABIRIN', 'Buket Peulawi', 'Aceh Timur', 'Nurussalam', 2000000, 'Pekerja Tambang', 'Tidak', 'SD', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Tidak'),
	(130, 'SURIYANTO RAJINI', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 2000000, 'Pekerja Tambang', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Ya'),
	(131, 'MASLAN GUNAWAN', 'Bukit Tiga', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Ya', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Ya', 'Ya'),
	(132, 'BUJANG IDRIS', 'Jalan Dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Petani', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya'),
	(133, 'SYUKUR', 'Buket Drien', 'Aceh Timur', 'Nurussalam', 2000000, 'Petani', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Ya', 'Ya'),
	(134, 'RINA RISWARDANI', 'Bukit Tiga', 'Aceh Timur', 'Nurussalam', 500000, 'Pembantu', 'Ya', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Ya'),
	(135, 'SARWONO AMSAR', 'Alue Dua Muka O', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Tidak', 'SD', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak'),
	(136, 'KASNO SUAIDI', 'Jalan Dua', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Tidak', 'SD', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Tidak'),
	(137, 'RUDI HARTONO', 'Bukit Tiga', 'Aceh Timur', 'Nurussalam', 2000000, 'Pembantu', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Tidak'),
	(138, 'SAMSIAR SIDER', 'Arul Pinang', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak'),
	(139, 'SARWONO AMSAR', 'Alue Dua Muka O', 'Aceh Timur', 'Nurussalam', 500000, 'Pekerja Tambang', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak'),
	(140, 'SAKA UMAR', 'Buket Peulawi', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SD', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak'),
	(141, 'ADITYA JULI NUGROHO', 'Buket Peulawi', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Ya'),
	(142, 'DARMI', 'Peunaron Lama', 'Aceh Timur', 'Nurussalam', 2000000, 'Pembantu', 'Ya', 'SMP', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak'),
	(143, 'JUANDA', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SMP', 'Sewa', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya'),
	(144, 'MARZUKI', 'Arul Pinang', 'Aceh Timur', 'Nurussalam', 2000000, 'Tukang', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak'),
	(145, 'MU SEN LIM', 'Gunong Putoh', 'Aceh Timur', 'Nurussalam', 500000, 'Petani', 'Tidak', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya'),
	(146, 'BILY YULIANTO', 'Jalan Dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Ya', 'Ya', 'Tidak', 'Tidak'),
	(147, 'ASMADI', 'Jalan Dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Ya', 'SMA', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak'),
	(148, 'AAN SUTIAWAN', 'Jalan Dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Ya'),
	(149, 'BELYBOY', 'Bukit Tiga', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Ya', 'SD', 'Sewa', 'Ya', 'Ya', 'Ya', 'Tidak', 'Tidak'),
	(150, 'MUHAMMAD KHOIFIN', 'Buket Peulawi', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Ya'),
	(151, 'TOMY', 'Peunaron Lama', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak'),
	(152, 'RICO MUNJIRI', 'Alue Jagat', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Tidak'),
	(153, 'NINARI', 'Peunaron Lama', 'Aceh Timur', 'Nurussalam', 500000, 'Petani', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak'),
	(154, 'DARUL', 'Buket Peulawi', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Ya', 'SMP', 'Sewa', 'Ya', 'Ya', 'Ya', 'Tidak', 'Tidak'),
	(155, 'NELI', 'Jalan Dua', 'Aceh Timur', 'Nurussalam', 500000, 'Petani', 'Ya', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Ya'),
	(156, 'REMO SAPUTRA', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya'),
	(157, 'FIRMAN SABHI YAUMAR', 'Blang Rambong', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Ya', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Ya'),
	(158, 'IMAN', 'Alue Jagat', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Ya', 'SD', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Ya'),
	(159, 'PARDI', 'Blang Rambong', 'Aceh Timur', 'Nurussalam', 2000000, 'Tukang', 'Ya', 'SMP', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya'),
	(160, 'LIU MUI FA', 'Peunaron Lama', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Ya', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Ya'),
	(161, 'MUHDI', 'Bantayan Timur', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Ya', 'SMA', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Ya'),
	(162, 'URAY DENI', 'Alue Dua Muka O', 'Aceh Timur', 'Nurussalam', 500000, 'Kuli Bangunan', 'Ya', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya'),
	(163, 'AHMAD GAZALI', 'Jalan Dua', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Ya', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak'),
	(164, 'ARDIANTO', 'Arul Pinang', 'Aceh Timur', 'Nurussalam', 2000000, 'Petani', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya'),
	(165, 'BANDI BUHARI', 'Bukit Tiga', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya'),
	(166, 'MASLAN GUNAWAN', 'Gunong Putoh', 'Aceh Timur', 'Nurussalam', 2000000, 'Petani', 'Ya', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak'),
	(167, 'RURAT', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya'),
	(168, 'PARINO SIDUK', 'Gunong Putoh', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Ya'),
	(169, 'ESTER G', 'Jalan Dua', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SMP', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak'),
	(170, 'HADNI HAIRUDIN', 'Peunaron Lama', 'Aceh Timur', 'Nurussalam', 2000000, 'Kuli Bangunan', 'Tidak', 'SD', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Ya', 'Ya'),
	(171, 'SA\'DIAH CALISTA', 'Bantayan Timur', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak'),
	(172, 'HAIYUDI', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak'),
	(173, 'SUPARDI', 'Peunaron Lama', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya'),
	(174, 'ARDI HAMIDI', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Tidak'),
	(175, 'MUHAMMAD ASLAN', 'Alue Dua Muka O', 'Aceh Timur', 'Nurussalam', 2000000, 'Pembantu', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Ya', 'Ya'),
	(176, 'EDDY SISWANTO', 'Bantayan Timur', 'Aceh Timur', 'Nurussalam', 1500000, 'Pekerja Tambang', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Tidak'),
	(177, 'JUNAIDI BAHRUN', 'Peunaron Lama', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya'),
	(178, 'JUANDA', 'Bantayan Timur', 'Aceh Timur', 'Nurussalam', 500000, 'Buruh', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Ya'),
	(179, 'ALDIANSYAH RIDWAN', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 500000, 'Pekerja Tambang', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Ya', 'Ya', 'Ya', 'Tidak'),
	(180, 'SURYANTO', 'Blang Rambong', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Ya', 'SMA', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Ya', 'Ya'),
	(181, 'SEMIL', 'Arul Pinang', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Tidak', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak'),
	(182, 'SULAIMAN', 'Bantayan Timur', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak'),
	(183, 'MUSPA ', 'Jalan Dua', 'Aceh Timur', 'Nurussalam', 2000000, 'Kuli Bangunan', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Ya', 'Ya'),
	(184, 'KARIM', 'Alue Dua Muka O', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Ya', 'SMP', 'Sewa', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Tidak'),
	(185, 'MATHANIN', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Ya'),
	(186, 'MUHAMMAD KHOIFIN', 'Buket Peulawi', 'Aceh Timur', 'Nurussalam', 1500000, 'Buruh', 'Ya', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya'),
	(187, 'MARGI', 'Blang Rambong', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Ya', 'Tidak'),
	(188, 'PUTRO WASONO', 'Arul Pinang', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Tidak', 'SD', 'Sewa', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Ya'),
	(189, 'ALI MURTOPO', 'Gunong Putoh', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Tidak', 'SMA', 'Sewa', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Ya'),
	(190, 'REMO SAPUTRA', 'Buket Peulawi', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SMP', 'Sewa', 'Tidak', 'Tidak', 'Tidak', 'Tidak', 'Ya'),
	(191, 'BAKHTIAR MA\'ARIF', 'Bantayan Timur', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Ya', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak'),
	(192, 'ILYAS ROMADHON', 'Arul Pinang', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Ya', 'SD', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Tidak'),
	(193, 'SULISTIYONO', 'Bantayan Timur', 'Aceh Timur', 'Nurussalam', 2000000, 'Pekerja Tambang', 'Ya', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya'),
	(194, 'NURAINI', 'Buket Drien', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Ya'),
	(195, 'DAVID DWI LIESTOYO', 'Peunaron Lama', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Ya', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya'),
	(196, 'ERNI', 'Blang Rambong', 'Aceh Timur', 'Nurussalam', 1000000, 'Buruh', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Ya'),
	(197, 'MALDINI MAWARDI', 'Buket Drien', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Ya', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Ya', 'Ya'),
	(198, 'SALIFASHTUL', 'Blang Rambong', 'Aceh Timur', 'Nurussalam', 1000000, 'Pekerja Tambang', 'Tidak', 'SMA', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak'),
	(199, 'SAKA UMAR', 'Bantayan Timur', 'Aceh Timur', 'Nurussalam', 1000000, 'Kuli Bangunan', 'Tidak', 'SD', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Ya', 'Tidak'),
	(200, 'RUSLI DURANI', 'Alue Dua Muka O', 'Aceh Timur', 'Nurussalam', 1500000, 'Tukang', 'Tidak', 'SD', 'Sewa', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya'),
	(201, 'YUNITA', 'Jalan Dua', 'Aceh Timur', 'Nurussalam', 1000000, 'Pembantu', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Ya'),
	(202, 'DESI TARMUJI', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Milik Sendiri', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Ya'),
	(203, 'HARDI SUMANTO', 'Buket Drien', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Tidak', 'SD', 'Milik Sendiri', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya'),
	(204, 'ENDANG', 'Blang Rambong', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Ya'),
	(205, 'RURAT', 'Bantayan Timur', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Tidak', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Tidak', 'Ya'),
	(206, 'JULINAWATI', 'Buket Drien', 'Aceh Timur', 'Nurussalam', 500000, 'Petani', 'Tidak', 'SD', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak'),
	(207, 'ESWAANDI', 'Peunaron Lama', 'Aceh Timur', 'Nurussalam', 1500000, 'Kuli Bangunan', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Tidak', 'Ya', 'Tidak', 'Ya'),
	(208, 'JANAWAR', 'Buket Peulawi', 'Aceh Timur', 'Nurussalam', 1500000, 'Petani', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak'),
	(209, 'ANDI MORNI', 'Arul Pinang', 'Aceh Timur', 'Nurussalam', 500000, 'Kuli Bangunan', 'Ya', 'SMP', 'Milik Sendiri', 'Ya', 'Tidak', 'Tidak', 'Ya', 'Ya'),
	(210, 'ZULKARNAEN', 'Buket Jok', 'Aceh Timur', 'Nurussalam', 1000000, 'Tukang', 'Tidak', 'SMA', 'Sewa', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
